build:
	docker build -t docker.pkg.github.com/johanbrandhorst/bazel-mono/go-server:latest -f ./Dockerfile ../..

publish:
	docker push docker.pkg.github.com/johanbrandhorst/bazel-mono/go-server:latest
